kind: Service
apiVersion: v1
metadata:
  name: hystirx
spec:
  type: NodePort
  selector:
    app: spring-cloud-hystrix
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 9999
    nodePort: 32003
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-hystrix
  labels:
    app: spring-cloud-hystrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-hystrix
  template:
    metadata:
      labels:
        app: spring-cloud-hystrix
        version: latest
    spec:
      hostname: hystrix
      subdomain: hystrix
      containers:
      - name: spring-cloud-hystrix
        image: 192.168.0.8:5000/hystrix-dashboard:latest
        ports:
        - name: http
          containerPort: 9999